

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 10)
```

```{r packages managments, echo = FALSE, message=FALSE, warning=FALSE}
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/00383/risk_factors_cervical_cancer.csv"

if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("GGally", quietly = TRUE)) install.packages("GGally")
if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages("tidyverse")
if (!requireNamespace("skimr", quietly = TRUE)) install.packages("skimr")
if (!requireNamespace("gtsummary", quietly = TRUE)) install.packages("gtsummary")
if (!requireNamespace("bookdown", quietly = TRUE)) install.packages("bookdown")
if (!requireNamespace("kableExtra", quietly = TRUE)) install.packages("kableExtra")
if (!requireNamespace("gridExtra", quietly = TRUE)) install.packages("gridExtra")
if (!requireNamespace("grid", quietly = TRUE)) install.packages("grid")
if (!requireNamespace("purrr", quietly = TRUE)) install.packages("purrr")
if (!requireNamespace("FactoMineR", quietly = TRUE)) install.packages("FactoMineR")
if (!requireNamespace("mice", quietly = TRUE)) install.packages("mice")


library(dplyr)
library(GGally) # plots
library(tidyverse)
library(skimr)
library(gtsummary) # patients characteristics
library(bookdown)
library(kableExtra) # tables aesthetics
library(gridExtra) # plots en colonnes 
library(heatmaply) # headmap + normalisation
library(grid) 
library(devtools)
library(purrr)
library(statReportPackage)
library(moments)#skewness kurtosis
library(FactoMineR)# ACP
library(explor)# visual acp, amc, fadm
library(missMDA)# imputation fadm
library(mice)#imputation 
library(lattice)#multiplot imputation display
library(VIM)#missing data vizualisation


```

```{r import data, echo = FALSE, message=FALSE, warning=FALSE}

#'________________________________________________
#'
#' LOAD DATA
#'________________________________________________

#data_original <- readr::read_csv(url)
data_original <- readr::read_csv('data_cervical_cancer.csv')

```


```{r settings txt files, echo = FALSE, message=FALSE, warning=FALSE}

#'________________________________________________
#'
#' TEXT FILES, DATABASE SETTINGS
#'________________________________________________


#variable patients set and feature sets

Feature_set <- "colnames.txt"
Feature_informations <- "col_informations.txt"

Total_set <- "total_set.txt"
Train_set <- "train_set.txt"
Test_set  <- "test_set.txt"

#path to patient sets 
path_txt <- "txt_file/"
path_to_Total_set <- paste0(path_txt,Total_set)
path_to_Train_set <- paste0(path_txt,Train_set)
path_to_Test_set  <- paste0(path_txt,Test_set)

#path to feature sets
path_txt <- "txt_file/"
path_to_Feature_set <- paste0(path_txt,Feature_set)
path_to_Feature_informations  <- paste0(path_txt,Feature_informations)


#set qualitative variables
nominal_variable_names <- c(
  "Smokes", "HormonalContraceptives", "IUD", "STDs", 
  "STDsCondylomatosis", "STDsCervicalCondylomatosis", 
  "STDsVaginalCondylomatosis", "STDsVulvoPerinealCondylomatosis", 
  "STDsSyphilis", "STDsPelvicInflammatoryDisease", "STDsGenitalHerpes", 
  "STDsMolluscumContagiosum", "STDsAIDS", "STDsHIV", "STDsHepatitisB", 
  "STDsHPV", "DxCancer", "DxCIN", "DxHPV", "Dx", "Hinselmann", 
  "Schiller", "Cytology", "Biopsy"
)
ordinal_variable_names <- c()

qualitative_variable_names <- c(nominal_variable_names,ordinal_variable_names)


#set quantitative variables
discrete_variable_names <- c(
  "NumberOfSexualPartners","FirstSexualIntercourse", "NumOfPregnancies", 
  "STDsNumber", "STDsNumberOfDiagnosis", "TimeSinceFirstSTDs", 
  "TimeSinceLastSTDs"
  )
continuous_variable_names <- c(
  "Age","SmokesYears", "SmokesPacksPerYear", 
  "HormonalContraceptivesYears", "IUDYears"
  )
quantitative_variable_names <- c(discrete_variable_names,continuous_variable_names)

#variable type list
bool_variable_list_names <- c("Smokes","HormonalContraceptives","DxCancer","DxCIN","DxHPV","Dx","Hinselmann","Schiller","Cytology","Biopsy","STDs","IUD","STDsCondylomatosis","STDsCervicalCondylomatosis","STDsVaginalCondylomatosis","STDsVulvoPerinealCondylomatosis","STDsSyphilis","STDsPelvicInflammatoryDisease","STDsGenitalHerpes","STDsMolluscumContagiosum","STDsAIDS","STDsHIV","STDsHepatitisB","STDsHPV")

#set outcome variable
Outcome = "DxCancer"
```






